steps:
- name: "gcr.io/cloud-builders/git"
  args: ['fetch', '--unshallow']
- name: 'gcr.io/cloud-builders/npm'
  args: ['npm', 'run', 'install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['npm', 'run', 'bundle']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
